### ISSUE TITLE
Introduction in text

### ISSUE THREAD

**Issue by WenhaoSu** [auramaze/auramaze#42]
### User Story
An art lover wants to learn more about a work, so he use AuraMaze to find the test introductions.

### Acceptance Criteria
The text intro is correct and informative.

**Comment by chaogedebishi** [comment]
https://github.com/auramaze/auramaze/blob/master/server/elasticsearch/art_mapping.json
https://github.com/auramaze/auramaze/blob/master/server/api/routes/search.js
